const AppRoutes = {
  AUTH: 'Auth',
  SIGN_IN: 'Sign In',
  SIGN_UP: 'Sign Up',
  PROFILE_EDIT: 'Profile Edit',
  RESET_PASSWORD: 'Reset Passrord',
  HOME: 'Home',
  PROFILE: 'Profile',
  ABOUT: 'About',
  ADDRESS_EDIT: 'Address Edit',
  ADDRESS_ADD: 'Address Add',
  CART: 'Cart',
  LOGIN: 'Login',
  REGISTER: 'Register',
  SETTINGS: 'Settings',
  ORDERS: 'Orders',
  SERVICE_HELP: 'Service / Help',
  PRIVACY_POLICY: 'Privacy Policy',
  CATEGORIES: 'Categories',
  ORDER_DETAIL: 'Order Detail',
  USER_ADDRESSES: 'User Addresses',
  CATEGORIES_PRODUCTS: 'Categories products',
  SEARCH: 'Search',
  WHISLIT: 'Whislist',
  PRODUCT_DETAIL: 'Product Detail',
  CART_SHIPPING: 'Shipping',
  CART_PAYMENT: 'Payment',
  CHECKOUT_WIZARD: 'Checkout',
  CHECKOUT_ORDER: 'Checkout Order',
  LOCAL_NOTIFICATION: 'Notifications',
  PASSWORD_EDIT: 'Password Change',
  ABOUT_SHOP: 'About Shop',
  ADDRESSES: 'Addresses'
};

export default AppRoutes;
